name: multi_lang_bad_words_filter
description: A multilingual bad words filtering package supporting English, Persian, Arabic, Turkish, and more.
version: 0.0.2
license: MIT
homepage: https://github.com/NegarTavakol/multi_lang_bad_words_filter
repository: https://github.com/NegarTavakol/multi_lang_bad_words_filter
issue_tracker: https://github.com/NegarTavakol/multi_lang_bad_words_filter/issues
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
