/// Schimpfwörter (Fäkalsprache)
const List<String> badWordsDe = [
  'scheiße',
  'arschloch',
  'hurensohn',
  'wichser',
  'idiot',
  'dummkopf',
  'verdammt',
  'miststück',
  'spasti',
  'penner',
  'blödmann',
  'fuck',
  'wichse',
  'bastard',
  'fick dich',
  'schlampe',
  'kacke',
  'nutte',
  'arsch',
  'schwanzlutscher',
  'drecksack',
  'kotzbrocken',
];

/// Sensible Begriffe (Sex, Gewalt, Drogen, Suizid etc.)
const List<String> sensitiveWordsDe = [
  // 🔞 Sexuelle Begriffe
  'sex',
  'porno',
  'nackt',
  'blasen',
  'busen',
  'vagina',
  'penis',
  'orgasmus',
  'masturbation',
  'ejakulation',
  'dildo',
  'hure',
  'camgirl',
  'onlyfans',
  'sexting',
  'nacktfoto',
  'ficken',
  'triplette',
  'gangbang',
  'creampie',
  'nsfw',


  // ⚠️ Selbstmord / Selbstverletzung
  'selbstmord',
  'ich will sterben',
  'ich bringe mich um',
  'ritzen',
  'leben beenden',
  'ich hasse mein leben',
  'leben ist sinnlos',
  'ich bin nutzlos',
  'wunsch zu sterben',
  'ich will nicht mehr leben',


  // 🔪 Gewalt / Sadismus / Bedrohung
  'töten',
  'ich töte dich',
  'erstechen',
  'vergewaltigung',
  'sadist',
  'blutbad',
  'foltern',
  'massaker',
  'schulmassaker',
  'abschlachten',
  'enthaupten',
  'blutig',
  'ich bringe euch alle um',


  // 💊 Drogen
  'kokain',
  'heroin',
  'crack',
  'gras',
  'haschisch',
  'überdosis',
  'droge',
  'xtc',
  'mdma',
  'benzodiazepin',
  'fentanyl',
  'süchtig',
  'fixen',


  // 🔫 Waffen / Terror / Bedrohung
  'bombe',
  'messer',
  'gewehr',
  'pistole',
  'anschlag',
  'geisel',
  'attentat',
  'terrorist',
  'kalaschnikow',
  'sprengstoff',
  'granate',
  'tötungsliste',
  'islamist',

];
