/// Insultos y malas palabras comunes en español
const List<String> badWordsEs = [
  'mierda',
  'puta',
  'gilipollas',
  'idiota',
  'cabron',
  'coño',
  'pendejo',
  'maricón',
  'zorra',
  'imbécil',
  'culero',
  'estúpido',
  'jodido',
  'malparido',
  'hijo de puta',
  'perra',
  'pelotudo',
  'boludo',
  'verga',
  'mamón',
  'culiao',
];

/// Términos sensibles: sexo, violencia, suicidio, drogas, amenazas
const List<String> sensitiveWordsEs = [
  // 🔞 Contenido sexual
  'sexo',
  'porno',
  'desnudo',
  'tetas',
  'polla',
  'vagina',
  'orgasmo',
  'masturbación',
  'eyaculación',
  'dildo',
  'coger',
  'follar',
  'trío',
  'prostituta',
  'lencería',
  'sexo anal',
  'chupar',


  // ⚠️ Suicidio / autolesión
  'suicidio',
  'me quiero morir',
  'voy a matarme',
  'cortarme',
  'terminar mi vida',
  'odio vivir',
  'no quiero vivir',
  'no le veo sentido a la vida',

  // 🔪 Violencia / amenazas / sadismo
  'asesinar',
  'te mataré',
  'violación',
  'tortura',
  'sádico',
  'baño de sangre',
  'masacre',
  'apuñalar',
  'decapitar',
  'quemar vivo',
  'desmembrar',
  'te voy a violar'

  // 💊 Drogas
  'cocaína',
  'heroína',
  'marihuana',
  'crack',
  'droga',
  'adicto',
  'sobredosis',
  'lsd',
  'metanfetamina',
  'xtc',
  'pastillas',
  'hachís',

  // 🔫 Armas / terrorismo / amenazas físicas
  'pistola',
  'cuchillo',
  'bomba',
  'explosivo',
  'terrorista',
  'tomar rehenes',
  'arma de fuego',
  'dispararte',
];
