/// Yaygın küfür ve hakaretler (Türkçe)
const List<String> badWordsTr = [
  'salak',
  'aptal',
  'gerizekalı',
  'oç',
  'orospu',
  'piç',
  'sikik',
  'amcık',
  'mal',
  'dangalak',
  'şerefsiz',
  'kaltak',
  'eşşek',
  'yarrak',
  'sürtük',
  'sik',
  'siktir',
  'sikik',
  'yavşak',
  'pezevenk',
  'yalama',
  'top',
  'ibne',
  'çük',
  'sübyancı',
  'kro',

];

/// Hassas konular: cinsellik, şiddet, intihar, uyuşturucu, tehdit
const List<String> sensitiveWordsTr = [
  // 🔞 Cinsel içerik
  'seks',
  'porno',
  'çıplak',
  'göt',
  'memeler',
  'vajina',
  'penis',
  'orgazm',
  'mastürbasyon',
  'dildo',
  'sikiş',
  'fuhuş',
  'üçlü ilişki',
  'liseli porno',
  'lezbiyen',
  'anal seks',
  'gay porno',
  'sağ elle yapmak',
  'azdırmak',
  'çırılçıplak',
  'erotik',


  // ⚠️ İntihar / kendine zarar verme
  'intihar',
  'ölmek istiyorum',
  'kendimi öldüreceğim',
  'canıma kıyacağım',
  'hayatıma son vereceğim',
  'kendimi kesiyorum',
  'yaşamak istemiyorum',
  'ölüm tek çare',
  'ölmeyi düşünüyorum',
  'benim için her şey bitti',
  'hayatım mahvoldu',
  'kendime zarar veriyorum',


  // 🔪 Şiddet / tehdit / sadizm
  'öldüreceğim',
  'öldürmek',
  'bıçaklamak',
  'tecavüz',
  'sadist',
  'işkence',
  'katliam',
  'kan banyosu',
  'parçalamak',
  'öldürürüm seni',
  'yakarım evini',
  'sana zarar vereceğim',
  'kurşunlayacağım',
  'kan gövdeyi götürecek',
  'kafanı kırarım',
  'seni doğrarım',


  // 💊 Uyuşturucu
  'eroin',
  'kokain',
  'esrar',
  'hap',
  'uyuşturucu',
  'bağımlı',
  'overdose',
  'metamfetamin',
  'lunapark',
  'bonzai',
  'extacy',
  'çakmak gazı',
  'kafa yapıcı',
  'ketamin',
  'uyuşturucu içmek',


  // 🔫 Silah / tehdit / terör
  'bomba',
  'tabanca',
  'silah',
  'terörist',
  'rehin',
  'patlatmak',
  'öldürmekle tehdit',
  'kesici alet',
  'roket',
  'kesici alet',
  'katliam yapacağım',
  'otomatik tüfek',
  'keserim seni',
  'terör saldırısı',
  'savaş suçu',

];
